=== kickstartDS/kickstartDS/packages/@rm-frontend/base/source/2-molecules/teaser-box/teaser-box-item.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://frontend.ruhmesmeile.com/base/molecules/teaser-box-item.schema.json",
  "title": "Teaser-Box Item",
  "description": "teaser-box-item",
  "type": "object",
  "properties": {
    "image": { "type": "string", "default": "default/images/dummy/16-9-s.png" },
    "topic": { "type": "string" },
    "text": { "type": "string" },
    "darkStyle": { "type": "boolean" },
    "ratio": {
      "type": "string",
      "enum": ["4:3", "16:9", "1:1"],
      "default": "16:9"
    },
    "imageSpacing": {
      "type": "boolean"
    },
    "link": {
      "allOf": [
        {
          "$ref": "http://frontend.ruhmesmeile.com/base/atoms/link-button.schema.json"
        },
        {
          "properties": {
            "hidden": { "type": "boolean" }
          }
        }
      ]
    }
  }
}

=== kickstartDS/kickstartDS/packages/@rm-frontend/base/source/2-molecules/teaser-box/teaser-box-item~dark-style.json
{
  "darkStyle": true,
  "image": "dummy/16-9-s.png",
  "topic": "Lorem Ipsum",
  "text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Lorem ispum dolor distinctio minima unde voluptatum aut. Lorem ipsum dolor sit amet.",
  "link": {
    "style": "solid-inverted",
    "label": "ruhmesmeile",
    "href": "https://ruhmesmeile.com/"
  }
}
